<?php
return [
    'BE' => [
        'debug' => true,
        'explicitADmode' => 'explicitAllow',
        'installToolPassword' => '$P$CsZzuA0rtPaT2OhPSVKC0FXxYAqr4U/',
        'loginSecurityLevel' => 'rsa',
        'versionNumberInFilename' => '0',
    ],
    'DB' => [
        'database' => 'db696756407',
        'host' => 'db696756407.db.1and1.com',
        'password' => 'typo3#34',
        'port' => 3306,
        'socket' => '',
        'username' => 'dbo696756407',
    ],
    'EXT' => [
        'extConf' => [
            'affiliate_manager' => 'a:0:{}',
            'bootstrap_grids' => 'a:1:{s:19:"enableGridSimpleRow";s:1:"0";}',
            'css_styled_content' => 'a:1:{s:32:"loadContentElementWizardTsConfig";s:1:"1";}',
            'easylogin2' => 'a:0:{}',
            'extension_builder' => 'a:3:{s:15:"enableRoundtrip";s:1:"1";s:15:"backupExtension";s:1:"1";s:9:"backupDir";s:35:"uploads/tx_extensionbuilder/backups";}',
            'extension_builder-master' => 'a:3:{s:15:"enableRoundtrip";s:1:"1";s:15:"backupExtension";s:1:"1";s:9:"backupDir";s:35:"uploads/tx_extensionbuilder/backups";}',
            'femanager' => 'a:2:{s:13:"disableModule";s:1:"0";s:10:"disableLog";s:1:"0";}',
            'gkh_rss_import' => 'a:0:{}',
            'gridelements' => 'a:2:{s:20:"additionalStylesheet";s:0:"";s:19:"nestingInListModule";s:1:"0";}',
            'metaseo' => 'a:4:{s:10:"pagingSize";s:0:"";s:10:"enableBeta";s:0:"";s:23:"enableIntegrationTTNews";s:1:"1";s:29:"sitemap_clearCachePossibility";s:0:"";}',
            'news' => 'a:16:{s:13:"prependAtCopy";s:1:"1";s:6:"tagPid";s:1:"1";s:12:"rteForTeaser";s:1:"0";s:22:"contentElementRelation";s:1:"1";s:21:"contentElementPreview";s:1:"1";s:13:"manualSorting";s:1:"0";s:19:"categoryRestriction";s:11:"current_pid";s:34:"categoryBeGroupTceFormsRestriction";s:1:"0";s:19:"dateTimeNotRequired";s:1:"0";s:11:"archiveDate";s:4:"date";s:12:"mediaPreview";s:5:"false";s:24:"showAdministrationModule";s:1:"1";s:35:"hidePageTreeForAdministrationModule";s:1:"0";s:12:"showImporter";s:1:"0";s:18:"storageUidImporter";s:1:"1";s:22:"resourceFolderImporter";s:12:"/news_import";}',
            'ods_ajaxmailsubscription' => 'a:0:{}',
            'perfectlightbox' => 'a:0:{}',
            'powermail' => 'a:8:{s:12:"disableIpLog";s:1:"0";s:27:"disableMarketingInformation";s:1:"0";s:20:"disableBackendModule";s:1:"0";s:24:"disablePluginInformation";s:1:"0";s:35:"disablePluginInformationMailPreview";s:1:"0";s:13:"enableCaching";s:1:"0";s:15:"l10n_mode_merge";s:1:"0";s:29:"replaceIrreWithElementBrowser";s:1:"0";}',
            'px_hybrid_auth' => 'a:3:{s:6:"basic.";a:3:{s:9:"login_pid";s:2:"32";s:10:"debug_mode";s:1:"1";s:10:"debug_file";s:0:"";}s:9:"provider.";a:3:{s:9:"facebook.";a:3:{s:7:"enabled";s:1:"1";s:2:"id";s:16:"1918837828390026";s:6:"secret";s:32:"43d43dd3a781d5e03bb3e58f97fa17b3";}s:9:"linkedin.";a:3:{s:7:"enabled";s:1:"0";s:3:"key";s:0:"";s:6:"secret";s:0:"";}s:5:"xing.";a:3:{s:7:"enabled";s:1:"0";s:3:"key";s:0:"";s:6:"secret";s:0:"";}}s:22:"auto_fe_user_creation.";a:2:{s:7:"enabled";s:1:"0";s:10:"storagePid";s:1:"4";}}',
            'realurl' => 'a:5:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:10:"moduleIcon";s:1:"0";}',
            'recycler' => 'a:0:{}',
            'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
            'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:1;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
            'social_auth' => 'a:2:{s:10:"providers.";a:4:{s:9:"facebook.";a:4:{s:7:"enabled";s:1:"1";s:5:"keys.";a:2:{s:2:"id";s:16:"1918837828390026";s:6:"secret";s:32:"43d43dd3a781d5e03bb3e58f97fa17b3";}s:5:"scope";s:5:"email";s:7:"display";s:5:"popup";}s:7:"google.";a:3:{s:7:"enabled";s:1:"1";s:5:"keys.";a:2:{s:2:"id";s:72:"727003266158-ge5s0hhg8ok8jrul7f7e5qfo0b06nhhm.apps.googleusercontent.com";s:6:"secret";s:24:"NZAc5Y9MaCrzpSL-OGJw_y1s";}s:5:"scope";s:48:"https://www.googleapis.com/auth/userinfo.profile";}s:8:"twitter.";a:2:{s:7:"enabled";s:1:"0";s:5:"keys.";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";}}s:9:"linkedin.";a:2:{s:7:"enabled";s:1:"0";s:5:"keys.";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";}}}s:6:"users.";a:4:{s:10:"storagePid";s:1:"4";s:12:"defaultGroup";s:1:"1";s:14:"fileStoragePid";s:1:"1";s:8:"filePath";s:11:"user_upload";}}',
            'sr_feuser_register' => 'a:3:{s:12:"uploadFolder";s:0:"";s:10:"imageTypes";s:44:"gif,jpg,jpeg,tif,tiff,bmp,pcx,tga,png,ai,svg";s:12:"imageMaxSize";s:4:"7168";}',
            't3colorbox' => 'a:0:{}',
            'tt_address' => 'a:3:{s:21:"backwardsCompatFormat";s:9:"%1$s %3$s";s:24:"storeBackwardsCompatName";s:1:"1";s:17:"readOnlyNameField";s:1:"1";}',
            'uncache' => 'a:0:{}',
            'vhs' => 'a:1:{s:20:"disableAssetHandling";s:1:"0";}',
        ],
    ],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'fr',
                'ja',
                'es',
            ],
        ],
    ],
    'FE' => [
        'cHashIncludePageId' => true,
        'debug' => true,
        'loginSecurityLevel' => 'rsa',
    ],
    'GFX' => [
        'colorspace' => 'RGB',
        'im' => 1,
        'im_mask_temp_ext_gif' => 1,
        'im_path' => '/usr/bin/',
        'im_path_lzw' => '/usr/bin/',
        'im_v5effects' => -1,
        'im_version_5' => 'gm',
        'image_processing' => 1,
        'jpg_quality' => '80',
    ],
    'INSTALL' => [
        'wizardDone' => [
            'TYPO3\CMS\Install\Updates\AccessRightParametersUpdate' => 1,
            'TYPO3\CMS\Install\Updates\BackendUserStartModuleUpdate' => 1,
            'TYPO3\CMS\Install\Updates\Compatibility6ExtractionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\ContentTypesToTextMediaUpdate' => 1,
            'TYPO3\CMS\Install\Updates\FileListIsStartModuleUpdate' => 1,
            'TYPO3\CMS\Install\Updates\FilesReplacePermissionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\LanguageIsoCodeUpdate' => 1,
            'TYPO3\CMS\Install\Updates\MediaceExtractionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\MigrateMediaToAssetsForTextMediaCe' => 1,
            'TYPO3\CMS\Install\Updates\MigrateShortcutUrlsAgainUpdate' => 1,
            'TYPO3\CMS\Install\Updates\OpenidExtractionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\PageShortcutParentUpdate' => 1,
            'TYPO3\CMS\Install\Updates\ProcessedFileChecksumUpdate' => 1,
            'TYPO3\CMS\Install\Updates\TableFlexFormToTtContentFieldsUpdate' => 1,
            'TYPO3\CMS\Install\Updates\WorkspacesNotificationSettingsUpdate' => 1,
            'TYPO3\CMS\Rtehtmlarea\Hook\Install\DeprecatedRteProperties' => 1,
            'TYPO3\CMS\Rtehtmlarea\Hook\Install\RteAcronymButtonRenamedToAbbreviation' => 1,
        ],
    ],
    'MAIL' => [
        'transport_sendmail_command' => '/usr/sbin/sendmail -t -i',
    ],
    'SYS' => [
        'caching' => [
            'cacheConfigurations' => [
                'extbase_object' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\VariableFrontend',
                    'groups' => [
                        'system',
                    ],
                    'options' => [
                        'defaultLifetime' => 0,
                    ],
                ],
            ],
        ],
        'clearCacheSystem' => false,
        'cookieSecure' => '2',
        'devIPmask' => '*',
        'displayErrors' => '1',
        'enableDeprecationLog' => false,
        'encryptionKey' => '5f38a9c787757a116a95df5405eb148215ea8cbe6d4a28713c1efe7a9a695f7f8bb7151a74472f9c240d13383d389193',
        'exceptionalErrors' => 20480,
        'isInitialDatabaseImportDone' => true,
        'isInitialInstallationInProgress' => false,
        'reverseProxySSL' => '*',
        'setMemoryLimit' => '1024',
        'sitename' => 'Typo 7.6.15',
        'sqlDebug' => 1,
        'systemLogLevel' => 2,
        't3lib_cs_convMethod' => 'mbstring',
        't3lib_cs_utils' => 'mbstring',
        'trustedHostsPattern' => '.*',
    ],
];
